=== momentum-design/momentum-design/packages/@momentum-design/token-builder/src/schemas/json/apps.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Welcome",
  "definitions": {
      "Welcome": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "fontFamilies": {
                  "$ref": "#/definitions/FontFamilies"
              },
              "lineHeights": {
                  "type": "object",
                  "additionalProperties": {
                      "$ref": "#/definitions/Ciscosans"
                  }
              },
              "fontWeights": {
                  "$ref": "#/definitions/FontWeights"
              },
              "fontSize": {
                  "type": "object",
                  "additionalProperties": {
                      "$ref": "#/definitions/Ciscosans"
                  }
              },
              "letterSpacing": {
                  "$ref": "#/definitions/Spacing"
              },
              "paragraphSpacing": {
                  "$ref": "#/definitions/Spacing"
              },
              "apps": {
                  "type": "object",
                  "additionalProperties": {
                      "$ref": "#/definitions/App"
                  }
              },
              "textCase": {
                  "$ref": "#/definitions/TextCaseClass"
              },
              "textDecoration": {
                  "$ref": "#/definitions/TextDecorationClass"
              }
          },
          "required": [
              "apps",
              "fontFamilies",
              "fontSize",
              "fontWeights",
              "letterSpacing",
              "lineHeights",
              "paragraphSpacing",
              "textCase",
              "textDecoration"
          ],
          "title": "Welcome"
      },
      "App": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "value": {
                  "$ref": "#/definitions/Value"
              },
              "type": {
                  "$ref": "#/definitions/Type"
              },
              "description": {
                  "type": "string"
              }
          },
          "required": [
              "description",
              "type",
              "value"
          ],
          "title": "App"
      },
      "Value": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "fontFamily": {
                  "$ref": "#/definitions/FontFamily"
              },
              "fontWeight": {
                  "$ref": "#/definitions/FontWeight"
              },
              "lineHeight": {
                  "type": "string"
              },
              "fontSize": {
                  "type": "string"
              },
              "letterSpacing": {
                  "$ref": "#/definitions/LetterSpacing"
              },
              "paragraphSpacing": {
                  "$ref": "#/definitions/ParagraphSpacing"
              },
              "paragraphIndent": {
                  "type": "string"
              },
              "textCase": {
                  "$ref": "#/definitions/TextCaseEnum"
              },
              "textDecoration": {
                  "$ref": "#/definitions/TextDecorationEnum"
              }
          },
          "required": [
              "fontFamily",
              "fontSize",
              "fontWeight",
              "letterSpacing",
              "lineHeight",
              "paragraphIndent",
              "paragraphSpacing",
              "textCase",
              "textDecoration"
          ],
          "title": "Value"
      },
      "FontFamilies": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "ciscosanstt": {
                  "$ref": "#/definitions/Ciscosans"
              },
              "ciscosans": {
                  "$ref": "#/definitions/Ciscosans"
              }
          },
          "required": [
              "ciscosans",
              "ciscosanstt"
          ],
          "title": "FontFamilies"
      },
      "Ciscosans": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "value": {
                  "type": "string"
              },
              "type": {
                  "type": "string"
              }
          },
          "required": [
              "type",
              "value"
          ],
          "title": "Ciscosans"
      },
      "FontWeights": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "ciscosanstt-0": {
                  "$ref": "#/definitions/Ciscosans"
              },
              "ciscosanstt-1": {
                  "$ref": "#/definitions/Ciscosans"
              },
              "ciscosans-2": {
                  "$ref": "#/definitions/Ciscosans"
              },
              "ciscosanstt-3": {
                  "$ref": "#/definitions/Ciscosans"
              },
              "ciscosanstt-4": {
                  "$ref": "#/definitions/Ciscosans"
              }
          },
          "required": [
              "ciscosans-2",
              "ciscosanstt-0",
              "ciscosanstt-1",
              "ciscosanstt-3",
              "ciscosanstt-4"
          ],
          "title": "FontWeights"
      },
      "Spacing": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "0": {
                  "$ref": "#/definitions/Ciscosans"
              }
          },
          "required": [
              "0"
          ],
          "title": "Spacing"
      },
      "TextCaseClass": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "none": {
                  "$ref": "#/definitions/Ciscosans"
              }
          },
          "required": [
              "none"
          ],
          "title": "TextCaseClass"
      },
      "TextDecorationClass": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "underline": {
                  "$ref": "#/definitions/Ciscosans"
              },
              "none": {
                  "$ref": "#/definitions/Ciscosans"
              }
          },
          "required": [
              "none",
              "underline"
          ],
          "title": "TextDecorationClass"
      },
      "Type": {
          "type": "string",
          "enum": [
              "typography"
          ],
          "title": "Type"
      },
      "FontFamily": {
          "type": "string",
          "enum": [
              "{fontFamilies.ciscosanstt}",
              "{fontFamilies.ciscosans}"
          ],
          "title": "FontFamily"
      },
      "FontWeight": {
          "type": "string",
          "enum": [
              "{fontWeights.ciscosanstt-3}",
              "{fontWeights.ciscosanstt-1}",
              "{fontWeights.ciscosanstt-0}",
              "{fontWeights.ciscosanstt-4}"
          ],
          "title": "FontWeight"
      },
      "LetterSpacing": {
          "type": "string",
          "enum": [
              "{letterSpacing.0}"
          ],
          "title": "LetterSpacing"
      },
      "ParagraphSpacing": {
          "type": "string",
          "enum": [
              "{paragraphSpacing.0}"
          ],
          "title": "ParagraphSpacing"
      },
      "TextCaseEnum": {
          "type": "string",
          "enum": [
              "{textCase.none}"
          ],
          "title": "TextCaseEnum"
      },
      "TextDecorationEnum": {
          "type": "string",
          "enum": [
              "{textDecoration.none}",
              "{textDecoration.underline}"
          ],
          "title": "TextDecorationEnum"
      }
  }
}

=== momentum-design/momentum-design/packages/@momentum-design/tokens/src/core/type/apps.json
{
  "fontFamilies": {
    "ciscosanstt": {
      "value": "CiscoSansTT",
      "type": "fontFamilies"
    },
    "ciscosans": {
      "value": "CiscoSans",
      "type": "fontFamilies"
    }
  },
  "lineHeights": {
    "0": {
      "value": "16",
      "type": "lineHeights"
    },
    "1": {
      "value": "20",
      "type": "lineHeights"
    },
    "2": {
      "value": "24",
      "type": "lineHeights"
    },
    "3": {
      "value": "28",
      "type": "lineHeights"
    },
    "4": {
      "value": "32",
      "type": "lineHeights"
    },
    "5": {
      "value": "40",
      "type": "lineHeights"
    },
    "6": {
      "value": "52",
      "type": "lineHeights"
    },
    "7": {
      "value": "64",
      "type": "lineHeights"
    }
  },
  "fontWeights": {
    "ciscosanstt-0": {
      "value": "Regular",
      "type": "fontWeights"
    },
    "ciscosanstt-1": {
      "value": "Medium",
      "type": "fontWeights"
    },
    "ciscosans-2": {
      "value": "Regular",
      "type": "fontWeights"
    },
    "ciscosanstt-3": {
      "value": "Bold",
      "type": "fontWeights"
    },
    "ciscosanstt-4": {
      "value": "Light",
      "type": "fontWeights"
    }
  },
  "fontSize": {
    "0": {
      "value": "12",
      "type": "fontSizes"
    },
    "1": {
      "value": "14",
      "type": "fontSizes"
    },
    "2": {
      "value": "16",
      "type": "fontSizes"
    },
    "3": {
      "value": "20",
      "type": "fontSizes"
    },
    "4": {
      "value": "24",
      "type": "fontSizes"
    },
    "5": {
      "value": "32",
      "type": "fontSizes"
    },
    "6": {
      "value": "40",
      "type": "fontSizes"
    },
    "7": {
      "value": "52",
      "type": "fontSizes"
    }
  },
  "letterSpacing": {
    "0": {
      "value": "0%",
      "type": "letterSpacing"
    }
  },
  "paragraphSpacing": {
    "0": {
      "value": "0",
      "type": "paragraphSpacing"
    }
  },
  "apps": {
    "body-underline-small_regular": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-0}",
        "lineHeight": "{lineHeights.0}",
        "fontSize": "{fontSize.0}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.underline}"
      },
      "type": "typography",
      "description": "Theme token: body-underline-small_regular; Core token: font-10. Needs prior approval from Momentum team to use."
    },
    "body-underline-small_medium": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-1}",
        "lineHeight": "{lineHeights.0}",
        "fontSize": "{fontSize.0}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.underline}"
      },
      "type": "typography",
      "description": "Theme token: body-underline-small_medium; Core token: font-10. Needs prior approval from Momentum team to use."
    },
    "body-underline-midsize_regular": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-0}",
        "lineHeight": "{lineHeights.1}",
        "fontSize": "{fontSize.1}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.underline}"
      },
      "type": "typography",
      "description": "Theme token: body-underline-middle_regular; Core token: font-20"
    },
    "body-underline-midsize_medium": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-1}",
        "lineHeight": "{lineHeights.1}",
        "fontSize": "{fontSize.1}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.underline}"
      },
      "type": "typography",
      "description": "Theme token: body-underline-middle_medium; Core token: font-20"
    },
    "body-underline-large_regular": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-0}",
        "lineHeight": "{lineHeights.2}",
        "fontSize": "{fontSize.2}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.underline}"
      },
      "type": "typography",
      "description": "Theme token: body-underline-large_regular; Core token: font-30"
    },
    "body-underline-large_medium": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-1}",
        "lineHeight": "{lineHeights.2}",
        "fontSize": "{fontSize.2}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.underline}"
      },
      "type": "typography",
      "description": "Theme token: body-underline-large_medium; Core token: font-30"
    },
    "body-small_regular": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosans}",
        "fontWeight": "{fontWeights.ciscosanstt-0}",
        "lineHeight": "{lineHeights.0}",
        "fontSize": "{fontSize.0}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token:body-small_regular; Core token: font-10. Needs prior approval from Momentum team to use."
    },
    "body-small_medium": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-1}",
        "lineHeight": "{lineHeights.0}",
        "fontSize": "{fontSize.0}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token:body-small_medium; Core token: font-10. Needs prior approval from Momentum team to use."
    },
    "body-small_bold": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-3}",
        "lineHeight": "{lineHeights.0}",
        "fontSize": "{fontSize.0}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token:body-small_bold; Core token: font-10. Needs prior approval from Momentum team to use."
    },
    "body-midsize_regular": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-0}",
        "lineHeight": "{lineHeights.1}",
        "fontSize": "{fontSize.1}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-middle_regular; Core token: font-20"
    },
    "body-midsize_medium": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-1}",
        "lineHeight": "{lineHeights.1}",
        "fontSize": "{fontSize.1}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-middle_medium; Core token: font-20"
    },
    "body-midsize_bold": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-3}",
        "lineHeight": "{lineHeights.1}",
        "fontSize": "{fontSize.1}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-middle_bold; Core token: font-20"
    },
    "body-large_regular": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosans}",
        "fontWeight": "{fontWeights.ciscosanstt-0}",
        "lineHeight": "{lineHeights.2}",
        "fontSize": "{fontSize.2}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "{paragraphIndent.0}",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-large_regular; Core token: font-30"
    },
    "body-large_medium": {
      "value": {
