=== momentum-design/momentum-design/packages/@momentum-design/token-builder/src/schemas/json/display.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Welcome",
  "definitions": {
      "Welcome": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "fontFamilies": {
                  "$ref": "#/definitions/FontFamilies"
              },
              "lineHeights": {
                  "type": "object",
                  "additionalProperties": {
                      "$ref": "#/definitions/Ciscosanstt"
                  }
              },
              "fontWeights": {
                  "$ref": "#/definitions/FontWeights"
              },
              "fontSize": {
                  "type": "object",
                  "additionalProperties": {
                      "$ref": "#/definitions/Ciscosanstt"
                  }
              },
              "letterSpacing": {
                  "$ref": "#/definitions/Spacing"
              },
              "paragraphSpacing": {
                  "$ref": "#/definitions/Spacing"
              },
              "display": {
                  "type": "object",
                  "additionalProperties": {
                      "$ref": "#/definitions/Display"
                  }
              },
              "textCase": {
                  "$ref": "#/definitions/Text"
              },
              "textDecoration": {
                  "$ref": "#/definitions/Text"
              }
          },
          "required": [
              "display",
              "fontFamilies",
              "fontSize",
              "fontWeights",
              "letterSpacing",
              "lineHeights",
              "paragraphSpacing",
              "textCase",
              "textDecoration"
          ],
          "title": "Welcome"
      },
      "Display": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "value": {
                  "$ref": "#/definitions/Value"
              },
              "type": {
                  "$ref": "#/definitions/Type"
              },
              "description": {
                  "type": "string"
              }
          },
          "required": [
              "description",
              "type",
              "value"
          ],
          "title": "Display"
      },
      "Value": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "fontFamily": {
                  "$ref": "#/definitions/FontFamily"
              },
              "fontWeight": {
                  "$ref": "#/definitions/FontWeight"
              },
              "lineHeight": {
                  "type": "string"
              },
              "fontSize": {
                  "type": "string"
              },
              "letterSpacing": {
                  "$ref": "#/definitions/LetterSpacing"
              },
              "paragraphSpacing": {
                  "$ref": "#/definitions/ParagraphSpacing"
              },
              "paragraphIndent": {
                  "type": "string"
              },
              "textCase": {
                  "$ref": "#/definitions/TextCase"
              },
              "textDecoration": {
                  "$ref": "#/definitions/TextDecoration"
              }
          },
          "required": [
              "fontFamily",
              "fontSize",
              "fontWeight",
              "letterSpacing",
              "lineHeight",
              "paragraphIndent",
              "paragraphSpacing",
              "textCase",
              "textDecoration"
          ],
          "title": "Value"
      },
      "FontFamilies": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "ciscosanstt": {
                  "$ref": "#/definitions/Ciscosanstt"
              }
          },
          "required": [
              "ciscosanstt"
          ],
          "title": "FontFamilies"
      },
      "Ciscosanstt": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "value": {
                  "type": "string"
              },
              "type": {
                  "type": "string"
              }
          },
          "required": [
              "type",
              "value"
          ],
          "title": "Ciscosanstt"
      },
      "FontWeights": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "ciscosanstt-0": {
                  "$ref": "#/definitions/Ciscosanstt"
              },
              "ciscosanstt-1": {
                  "$ref": "#/definitions/Ciscosanstt"
              },
              "ciscosanstt-2": {
                  "$ref": "#/definitions/Ciscosanstt"
              },
              "ciscosanstt-3": {
                  "$ref": "#/definitions/Ciscosanstt"
              }
          },
          "required": [
              "ciscosanstt-0",
              "ciscosanstt-1",
              "ciscosanstt-2",
              "ciscosanstt-3"
          ],
          "title": "FontWeights"
      },
      "Spacing": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "0": {
                  "$ref": "#/definitions/Ciscosanstt"
              }
          },
          "required": [
              "0"
          ],
          "title": "Spacing"
      },
      "Text": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "none": {
                  "$ref": "#/definitions/Ciscosanstt"
              }
          },
          "required": [
              "none"
          ],
          "title": "Text"
      },
      "Type": {
          "type": "string",
          "enum": [
              "typography"
          ],
          "title": "Type"
      },
      "FontFamily": {
          "type": "string",
          "enum": [
              "{fontFamilies.ciscosanstt}"
          ],
          "title": "FontFamily"
      },
      "FontWeight": {
          "type": "string",
          "enum": [
              "{fontWeights.ciscosanstt-2}",
              "{fontWeights.ciscosanstt-1}",
              "{fontWeights.ciscosanstt-0}",
              "{fontWeights.ciscosanstt-3}"
          ],
          "title": "FontWeight"
      },
      "LetterSpacing": {
          "type": "string",
          "enum": [
              "{letterSpacing.0}"
          ],
          "title": "LetterSpacing"
      },
      "ParagraphSpacing": {
          "type": "string",
          "enum": [
              "{paragraphSpacing.0}"
          ],
          "title": "ParagraphSpacing"
      },
      "TextCase": {
          "type": "string",
          "enum": [
              "{textCase.none}"
          ],
          "title": "TextCase"
      },
      "TextDecoration": {
          "type": "string",
          "enum": [
              "{textDecoration.none}"
          ],
          "title": "TextDecoration"
      }
  }
}

=== momentum-design/momentum-design/packages/@momentum-design/tokens/src/core/type/display.json
{
  "fontFamilies": {
    "ciscosanstt": {
      "value": "CiscoSansTT",
      "type": "fontFamilies"
    }
  },
  "lineHeights": {
    "0": {
      "value": "24",
      "type": "lineHeights"
    },
    "1": {
      "value": "28",
      "type": "lineHeights"
    },
    "2": {
      "value": "32",
      "type": "lineHeights"
    },
    "3": {
      "value": "40",
      "type": "lineHeights"
    },
    "4": {
      "value": "52",
      "type": "lineHeights"
    },
    "5": {
      "value": "64",
      "type": "lineHeights"
    },
    "6": {
      "value": "80",
      "type": "lineHeights"
    },
    "7": {
      "value": "100",
      "type": "lineHeights"
    },
    "8": {
      "value": "124",
      "type": "lineHeights"
    },
    "9": {
      "value": "124%",
      "type": "lineHeights"
    }
  },
  "fontWeights": {
    "ciscosanstt-0": {
      "value": "Regular",
      "type": "fontWeights"
    },
    "ciscosanstt-1": {
      "value": "Medium",
      "type": "fontWeights"
    },
    "ciscosanstt-2": {
      "value": "Bold",
      "type": "fontWeights"
    },
    "ciscosanstt-3": {
      "value": "Light",
      "type": "fontWeights"
    }
  },
  "fontSize": {
    "0": {
      "value": "16",
      "type": "fontSizes"
    },
    "1": {
      "value": "20",
      "type": "fontSizes"
    },
    "2": {
      "value": "24",
      "type": "fontSizes"
    },
    "3": {
      "value": "32",
      "type": "fontSizes"
    },
    "4": {
      "value": "40",
      "type": "fontSizes"
    },
    "5": {
      "value": "52",
      "type": "fontSizes"
    },
    "6": {
      "value": "64",
      "type": "fontSizes"
    },
    "7": {
      "value": "80",
      "type": "fontSizes"
    },
    "8": {
      "value": "100",
      "type": "fontSizes"
    }
  },
  "letterSpacing": {
    "0": {
      "value": "0%",
      "type": "letterSpacing"
    }
  },
  "paragraphSpacing": {
    "0": {
      "value": "0",
      "type": "paragraphSpacing"
    }
  },
  "display": {
    "body-small_regular": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-0}",
        "lineHeight": "{lineHeights.0}",
        "fontSize": "{fontSize.0}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-small_regular; Core token: font-30"
    },
    "body-small_medium": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-1}",
        "lineHeight": "{lineHeights.0}",
        "fontSize": "{fontSize.0}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-small_medium; Core token: font-30"
    },
    "body-small_bold": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-2}",
        "lineHeight": "{lineHeights.0}",
        "fontSize": "{fontSize.0}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-small_bold; Core token: font-30"
    },
    "body-midsize_regular": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-0}",
        "lineHeight": "{lineHeights.1}",
        "fontSize": "{fontSize.1}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-middle_regular; Core token: font-40"
    },
    "body-midsize_medium": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-1}",
        "lineHeight": "{lineHeights.1}",
        "fontSize": "{fontSize.1}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-middle_medium; Core token: font-40"
    },
    "body-midsize_bold": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-2}",
        "lineHeight": "{lineHeights.1}",
        "fontSize": "{fontSize.1}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-middle_bold; Core token: font-40"
    },
    "body-large_regular": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-0}",
        "lineHeight": "{lineHeights.2}",
        "fontSize": "{fontSize.2}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-large_regular; Core token: font-50"
    },
    "body-large_medium": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-1}",
        "lineHeight": "{lineHeights.2}",
        "fontSize": "{fontSize.2}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-large_medium; Core token: font-50"
    },
    "body-large_bold": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-2}",
        "lineHeight": "{lineHeights.2}",
        "fontSize": "{fontSize.2}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: body-large_bold; Core token: font-50"
    },
    "heading-small_regular": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-0}",
        "lineHeight": "{lineHeights.3}",
        "fontSize": "{fontSize.3}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: heading-small_regular; Core token: font-60"
    },
    "heading-small_medium": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-1}",
        "lineHeight": "{lineHeights.3}",
        "fontSize": "{fontSize.3}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: heading-small_medium; Core token: font-60"
    },
    "heading-small_bold": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-2}",
        "lineHeight": "{lineHeights.3}",
        "fontSize": "{fontSize.3}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: heading-small_bold; Core token: font-60"
    },
    "heading-midsize_regular": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-0}",
        "lineHeight": "{lineHeights.4}",
        "fontSize": "{fontSize.4}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: heading-middle_regular; Core token: font-70"
    },
    "heading-midsize_medium": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
        "fontWeight": "{fontWeights.ciscosanstt-1}",
        "lineHeight": "{lineHeights.4}",
        "fontSize": "{fontSize.4}",
        "letterSpacing": "{letterSpacing.0}",
        "paragraphSpacing": "{paragraphSpacing.0}",
        "paragraphIndent": "",
        "textCase": "{textCase.none}",
        "textDecoration": "{textDecoration.none}"
      },
      "type": "typography",
      "description": "Theme token: heading-middle_medium; Core token: font-70"
    },
    "heading-midsize_bold": {
      "value": {
        "fontFamily": "{fontFamilies.ciscosanstt}",
